config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'generate_signed_s3_url' => 'aws#generate_signed_s3_url'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords'}

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :homeworks, only: :show
  resources :diagnostic_exam, only: :show
  resources :diagnostic_exam_users, only: :create
  resources :practices, only: :show

  post 'subir-tarea' => 'homeworks_users#create', as: :homework_users

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :homeworks, except: :index
    resources :homeworks_users, only: [:show, :update, :destroy]
    resources :groups, except: :index
    resources :videos, except: :index
    resources :diagnostic_exams do
      resources :questions
    end
    resources :practices do
      resources :questions
    end
  end

end

app/models/diagnostic_exam.rb
class DiagnosticExam < ActiveRecord::Base
  has_and_belongs_to_many :users

  has_many :questions
  has_many :answers, through: :questions

  def check(params_answers)
    grade = 0
    question_value = 100.0 / questions.count
    params_answers.each do |answer|
      if answer[1].is_a?(Array)
        temp_question_value = question_value / answer[1].count
        answer[1].each do |answ|
          grade += temp_question_value if Question.find(answer[0]).check(answ)
        end
      else
        grade += question_value if Question.find(answer[0]).check(answer[1])
      end
    end
    grade.round(2)
  end
end

app/controllers/admin/diagnostic_exams_controller.rb
class Admin::DiagnosticExamsController < Admin::ApplicationController
  before_action :set_diagnostic_exam, only: [:show, :edit, :update, :destroy]

  def show
    @questions = Question.where(diagnostic_exam_id: @diagnostic_exam.id)
  end

  def new
    @diagnostic_exam = DiagnosticExam.new
  end

  def edit
    @questions = Question.where(diagnostic_exam_id: @diagnostic_exam.id)
  end

  def create
    @diagnostic_exam = DiagnosticExam.new(diagnostic_exam_params)
    authorize @diagnostic_exam

    if @diagnostic_exam.save
      redirect_to admin_dashboard_path(anchor: 'examenes_diagnositcos')
    else
      redirect_to admin_dashboard_path(anchor: 'examenes_diagnositcos')
    end
  end

  def update
    authorize @diagnostic_exam
    if @diagnostic_exam.update(diagnostic_exam_params)
      redirect_to admin_dashboard_path(anchor: 'examenes_diagnositcos')
    else
      redirect_to admin_dashboard_path(anchor: 'examenes_diagnositcos')
    end
  end

  def destroy
    authorize @diagnostic_exam
    @diagnostic_exam.destroy
  end

  private

  def set_diagnostic_exam
    @diagnostic_exam = DiagnosticExam.find(params[:id])
  end

  def diagnostic_exam_params
    params.require(:diagnostic_exam).permit(:subject)
  end
end

app/controllers/diagnostic_exam_controller.rb
class DiagnosticExamController < ApplicationController
  before_action :set_diagnostic_exam, only: :show
  skip_before_filter :check_first_diagnostic_exam

  def show
    @diagnostic_exam_user = DiagnosticExamUser.new
  end

  private

  def set_diagnostic_exam
    @diagnostic_exam = DiagnosticExam.find(params[:id])
  end

  # def diagnostic_exam_user_params
  #   params.require(:diagnostic_exam_user).permit(:diagnostic_exam_id, :user_id)
  # end
end

app/helpers/diagnostic_exam_helper.rb
module DiagnosticExamHelper
end

app/views/admin/diagnostic_exams/_form.html.erb
<%= simple_form_for [:admin, @diagnostic_exam] do |f| %>
  <%= display_flash_messages %>

  <%= f.input :subject, collection: Subject.subjects, include_blank: false %>

  <%= f.button :submit %>
<% end %>

app/views/admin/diagnostic_exams/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Editar Examen Diagnostico</h1>

    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <h4>Preguntas Actuales</h4>
  </div>
</div>

<div class="row">
  <% @questions.each do |question| %>
    <div class="small-12 columns">
      <%= markdown question.question %>
      <%= link_to 'Editar', edit_admin_diagnostic_exam_question_path(@diagnostic_exam, question) %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Agregar Preguntas', new_admin_diagnostic_exam_question_path(@diagnostic_exam), class: 'button tiny radius success' %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Regresar', admin_dashboard_path(anchor: 'examenes_diagnositcos'), class: 'button tiny radius' %>
  </div>
</div>

app/views/admin/diagnostic_exams/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Nuevo Examen Diagnostico</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Regresar', admin_dashboard_path(anchor: 'examenes_diagnositcos'), class: 'button tiny radius' %>
  </div>
</div>

app/views/admin/diagnostic_exams/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Examen Diagnostico - <%= @diagnostic_exam.subject %></h2>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <% @questions.each_with_index do |question, i| %>
      <div class="row">
        <div class="small-12 columns">
          <strong>Pregunta <%= i+1 %>:</strong>
          <%= markdown question.question %>
        </div>
      </div>
      <div class="row">
        <div class="small-12 columns">
          <% question.correct_answer.each do |correct_answers| %>
            Respuesta correcta: <%= correct_answers.answer %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Regresar', admin_dashboard_path(anchor: 'examenes_diagnositcos'), class: 'button tiny radius' %>
  </div>
</div>