config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'generate_signed_s3_url' => 'aws#generate_signed_s3_url'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords'}

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :homeworks, only: :show
  resources :diagnostic_exam, only: :show
  resources :diagnostic_exam_users, only: :create
  resources :practices, only: :show

  post 'subir-tarea' => 'homeworks_users#create', as: :homework_users

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :homeworks, except: :index
    resources :homeworks_users, only: [:show, :update, :destroy]
    resources :groups, except: :index
    resources :videos, except: :index
    resources :diagnostic_exams do
      resources :questions
    end
    resources :practices do
      resources :questions
    end
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @homeworks = Homework.all
    @pending_homeworks = HomeworkUser.all
    @groups = Group.all
    @diagnostic_exams = DiagnosticExam.all
    @practices = Practice.all
    @videos = Video.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @homeworks = HomeworkUser.homeworks(current_user)
    @pending_homeworks =  Homework.specifc_homeworks(subject: current_user.subject, level: current_user.level) - @homeworks
    @practices = Practice.all
    @video_hash = {}
    Subject.subjects.each do |subject|
      @video_hash.merge!(subject => Video.where(subject: subject))
    end
    flash[:warning] = "Tienes un Examen Diagnostico pendiente <strong>#{view_context.link_to 'ir a examen', next_diagnostic_exam_path}</strong>".html_safe if @pending_homeworks.empty?
  end

  private

  def next_diagnostic_exam_path
    diagnostic_exam_path(DiagnosticExam.where(subject: Subject.next(current_user.subject)).first.id)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def iframe_video(url)
    "<iframe width='640' height='360' src='#{url}?rel=0' frameborder='0' allowfullscreen></iframe>"
  end
end

app/views/dashboard/_calificaciones.html.erb
<table class="datatable">
  <thead>
    <tr>
      <th>Tema</th>
      <th>Calificación</th>
      <th>Comentarios</th>
    </tr>
  </thead>
  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.subject %></td>
        <td><%= homework.grade(current_user) %></td>
        <td><%= link_to(fa_icon('comments'), '#', data: { reveal_id: "commentarios_#{homework.id}" }) %></td>
      </tr>
      <div id="commentarios_<%= homework.id %>" class="reveal-modal" data-reveal>
        <h2>Comentario</h2>
        <p><%= homework.comment(current_user) %></p>
        <a class="close-reveal-modal">&#215;</a>
      </div>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_ejercicios.html.erb
<table class="datatable">
  <thead>
    <tr>
      <th>Tema</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= practice.subject %></td>
        <td><%= link_to 'Ver', practice_path(practice), class: 'button tiny radius no-margin' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_tareas.html.erb
<table class="datatable">
  <thead>
    <tr>
      <th>Tema</th>
      <th>Fecha Limite</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pending_homeworks.each do |homework| %>
      <tr>
        <td><%= homework.subject %></td>
        <td><%= homework.deadline %></td>
        <td><%= link_to 'Ver', homework_path(homework), class: 'button tiny radius no-margin' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_videos.html.erb
<div class="row">
  <div class="small-12 columns">
    <% @video_hash.each do |subject, videos| %>
      <div class="row">
        <div class="small-12">
          <h3><%= subject %></h3>
          <div class="row">
            <% videos[0..-2].each do |video| %>
              <div class="small-4 columns">
                <div class="flex-video">
                  <%= raw iframe_video(video.url) %>
                </div>
              </div>
            <% end %>
            <div class="small-4 columns end">
              <div class="flex-video">
                <%= raw iframe_video(videos.last.url) if !videos.empty? %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="small-6 columns end">
    <h2><%= fa_icon 'tachometer' %> Dashboard</h2>
  </div>
</div>
<%= display_flash_messages %>
<div class="row">
  <div class="small-12 columns">
    <dl class="tabs" data-tab data-options="deep_linking:true">
      <dd class="active"><a href="#tareas-pendientes"><%= fa_icon 'files-o' %> Tareas Pendientes</a></dd>
      <dd><a href="#calificaciones"><%= fa_icon 'files-o' %> Calificaciones</a></dd>
      <dd><a href="#ejercicios"><%= fa_icon 'bicycle' %> Ejercicios</a></dd>
      <dd><a href="#videos"><%= fa_icon 'video-camera' %> Videos</a></dd>
    </dl>
    <div class="tabs-content">
      <div class="content active" id="tareas-pendientes">
        <%= render 'tareas' %>
      </div>
      <div class="content" id="calificaciones">
        <%= render 'calificaciones' %>
      </div>
      <div class="content" id="ejercicios">
        <%= render 'ejercicios' %>
      </div>
      <div class="content" id="videos">
        <%= render 'videos' %>
      </div>
    </div>
  </div>
</div>