config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'generate_signed_s3_url' => 'aws#generate_signed_s3_url'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords'}

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :homeworks, only: :show
  resources :diagnostic_exam, only: :show
  resources :diagnostic_exam_users, only: :create
  resources :practices, only: :show

  post 'subir-tarea' => 'homeworks_users#create', as: :homework_users

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :homeworks, except: :index
    resources :homeworks_users, only: [:show, :update, :destroy]
    resources :groups, except: :index
    resources :videos, except: :index
    resources :diagnostic_exams do
      resources :questions
    end
    resources :practices do
      resources :questions
    end
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @homeworks = Homework.all
    @pending_homeworks = HomeworkUser.all
    @groups = Group.all
    @diagnostic_exams = DiagnosticExam.all
    @practices = Practice.all
    @videos = Video.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @homeworks = HomeworkUser.homeworks(current_user)
    @pending_homeworks =  Homework.specifc_homeworks(subject: current_user.subject, level: current_user.level) - @homeworks
    @practices = Practice.all
    @video_hash = {}
    Subject.subjects.each do |subject|
      @video_hash.merge!(subject => Video.where(subject: subject))
    end
    flash[:warning] = "Tienes un Examen Diagnostico pendiente <strong>#{view_context.link_to 'ir a examen', next_diagnostic_exam_path}</strong>".html_safe if @pending_homeworks.empty?
  end

  private

  def next_diagnostic_exam_path
    diagnostic_exam_path(DiagnosticExam.where(subject: Subject.next(current_user.subject)).first.id)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def iframe_video(url)
    "<iframe width='640' height='360' src='#{url}?rel=0' frameborder='0' allowfullscreen></iframe>"
  end
end

app/views/admin/dashboard/_ejercicios.html.erb
<%= link_to 'Crear un Ejercicio', new_admin_practice_path, class: 'button tiny radius' %>

<table class="datatable">
  <thead>
    <tr>
      <th>Subject</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @practices.each do |practice| %>
    <tr>
      <td><%= practice.subject %></td>
      <td>
        <%= link_to 'Ver', admin_practice_path(practice), class: 'button tiny radius no-margin' %>
        <%= link_to 'Editar', edit_admin_practice_path(practice), class: 'button tiny radius no-margin' %>
        <%= link_to 'Borrar', admin_practice_path(practice), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius alert no-margin' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dashboard/_examenes_diagnositcos.html.erb
<%= link_to 'Crear un Examen Diagnositco', new_admin_diagnostic_exam_path, class: 'button tiny radius' %>

<table class="datatable">
  <thead>
    <tr>
      <th>Subject</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @diagnostic_exams.each do |diagnostic_exam| %>
      <tr>
        <td><%= diagnostic_exam.subject %></td>
        <td>
          <%= link_to 'Ver', admin_diagnostic_exam_path(diagnostic_exam), class: 'button tiny radius no-margin' %>
          <%= link_to 'Editar', edit_admin_diagnostic_exam_path(diagnostic_exam), class: 'button tiny radius no-margin' %>
          <%= link_to 'Borrar', admin_diagnostic_exam_path(diagnostic_exam), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius alert no-margin' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dashboard/_grupos.html.erb
<%= link_to 'Crear Grupo', new_admin_group_path, class: 'button tiny radius' %>

<table class="datatable">
  <thead>
    <tr>
      <th>Horario</th>
      <th>Nombre</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.schedule %></td>
        <td><%= group.name %></td>
        <td>
          <%= link_to 'Editar', edit_admin_group_path(group), class: 'button tiny radius no-margin' %>
          <%= link_to 'Borrar', admin_groups_path(group), class: 'button tiny radius alert no-margin', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dashboard/_metricas.html.erb
aqui metricas

app/views/admin/dashboard/_revisar_tareas.html.erb
<table class="datatable">
  <thead>
    <tr>
      <th>Matricula</th>
      <th>Subject/File</th>
      <th>Delivered</th>
      <th>Grade</th>
      <th>Comment</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pending_homeworks.each do |pending_homework| %>
      <tr>
        <td><%= pending_homework.user.email.tr('@itesm.mx','') %></td>
        <td><%= link_to pending_homework.homework.subject, pending_homework.url %></td>
        <td><%= pending_homework.created_at %></td>
        <td><%= click_to_edit pending_homework, path: admin_homeworks_user_path(pending_homework), attribute: :inline_grade %></td>
        <td><%= click_to_edit pending_homework, path: admin_homeworks_user_path(pending_homework), attribute: :inline_comment %></td>
        <td><%= link_to 'Borrar', admin_homeworks_user_path(pending_homework), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius alert no-margin' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dashboard/_tareas.html.erb
<%= link_to 'Crear Tarea', new_admin_homework_path, class: 'button tiny radius' %>

<table class="datatable">
  <thead>
    <tr>
      <th>Level</th>
      <th>Type</th>
      <th>Subject</th>
      <th>Deadline</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.level %></td>
        <td><%= homework.hw_type %></td>
        <td><%= link_to homework.subject, admin_homework_path(homework) %></td>
        <td><%= homework.deadline %></td>
        <td>
          <%= link_to 'Editar', edit_admin_homework_path(homework), class: 'button tiny radius no-margin' %>
          <%= link_to 'Borrar', admin_homework_path(homework), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny radius alert no-margin' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dashboard/_videos.html.erb
<%= link_to 'Crear Video', new_admin_video_path, class: 'button tiny radius' %>

<table class="datatable">
  <thead>
    <tr>
      <th>Video</th>
      <th>Subject</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
    <tr>
      <td><%= link_to video.title, video.url %></td>
      <td><%= video.subject %></td>
      <td>
        <%= link_to 'Editar', edit_admin_video_path(video), class: 'button tiny radius no-margin' %>
        <%= link_to 'Borrar', admin_video_path(video), class: 'button tiny radius alert no-margin', method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dashboard/index.html.erb
<div class="row">
  <div class="small-6 columns end">
    <h2><%= fa_icon 'tachometer' %> Dashboard</h2>
  </div>
</div>
<%= display_flash_messages %>
<div class="row">
  <div class="small-12 columns">
    <dl class="tabs" data-tab data-options="deep_linking:true">
      <dd class="active"><a href="#revisar_tareas"><%= fa_icon 'files-o' %> Revisar Tareas</a></dd>
      <dd ><a href="#tareas"><%= fa_icon 'files-o' %> Tareas</a></dd>
      <dd><a href="#grupos"><%= fa_icon 'users' %> Grupos</a></dd>
      <dd><a href="#examenes_diagnositcos"><%= fa_icon 'stethoscope' %> Examenes Diagnosticos</a></dd>
      <dd><a href="#ejercicios"><%= fa_icon 'bicycle' %> Ejercicios</a></dd>
      <dd><a href="#videos"><%= fa_icon 'video-camera' %> Videos</a></dd>
      <!-- <dd><a href="#metricas"><%#= fa_icon 'bar-chart' %> Metricas</a></dd> -->
    </dl>
    <div class="tabs-content">
      <div class="content active" id="revisar_tareas">
        <%= render 'revisar_tareas' %>
      </div>
      <div class="content" id="tareas">
        <%= render 'tareas' %>
      </div>
      <div class="content" id="examenes_diagnositcos">
        <%= render 'examenes_diagnositcos' %>
      </div>
      <div class="content" id="ejercicios">
        <%= render 'ejercicios' %>
      </div>
      <div class="content" id="grupos">
        <%= render 'grupos' %>
      </div>
      <div class="content" id="videos">
        <%= render 'videos' %>
      </div>
      <!-- <div class="content" id="metricas">
        <%#= render 'metricas' %>
      </div> -->
    </div>
  </div>
</div>