config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'generate_signed_s3_url' => 'aws#generate_signed_s3_url'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords'}

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :homeworks, only: :show
  resources :diagnostic_exam, only: :show
  resources :diagnostic_exam_users, only: :create
  resources :practices, only: :show

  post 'subir-tarea' => 'homeworks_users#create', as: :homework_users

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :homeworks, except: :index
    resources :homeworks_users, only: [:show, :update, :destroy]
    resources :groups, except: :index
    resources :videos, except: :index
    resources :diagnostic_exams do
      resources :questions
    end
    resources :practices do
      resources :questions
    end
  end

end

app/models/practice.rb
class Practice < ActiveRecord::Base
  has_many :questions
  has_many :answers, through: :questions
end

app/controllers/admin/practices_controller.rb
class Admin::PracticesController < Admin::ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]

  def show
    @questions = Question.where(practice_id: @practice.id)
  end

  def new
    @practice = Practice.new
  end

  def edit
    @questions = Question.where(practice_id: @practice.id)
  end

  def create
    @practice = Practice.new(practice_params)
    authorize @practice

    if @practice.save
      redirect_to admin_dashboard_path(anchor: 'ejercicios')
    else
      redirect_to admin_dashboard_path(anchor: 'ejercicios')
    end
  end

  def update
    authorize @practice
    if @practice.update(practice_params)
      redirect_to admin_dashboard_path(anchor: 'ejercicios')
    else
      redirect_to admin_dashboard_path(anchor: 'ejercicios')
    end
  end

  def destroy
    authorize @practice
    @practice.destroy
  end

  private

  def set_practice
    @practice = Practice.find(params[:id])
  end

  def practice_params
    params.require(:practice).permit(:subject)
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  def show
    @practice = Practice.find(params[:id])
  end
end

app/views/admin/practices/_form.html.erb
<%= simple_form_for [:admin, @practice] do |f| %>
  <%= display_flash_messages %>

  <%= f.input :subject, collection: Subject.subjects, include_blank: false %>

  <%= f.button :submit %>
<% end %>

app/views/admin/practices/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Editar Ejercicio</h1>
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <h4>Preguntas Actuales</h4>
  </div>
</div>

<div class="row">
  <% @questions.each do |question| %>
    <div class="small-12 columns">
      <%= markdown question.question %>
      <%= link_to 'Editar', edit_admin_practice_question_path(@practice, question) %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Agregar Preguntas', new_admin_practice_question_path(@practice), class: 'button tiny radius success' %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Regresar', admin_dashboard_path(anchor: 'ejercicios'), class: 'button tiny radius' %>
  </div>
</div>

app/views/admin/practices/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Nuevo Ejercico</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Regresar', admin_dashboard_path(anchor: 'ejercicios'), class: 'button tiny radius' %>
  </div>
</div>

app/views/admin/practices/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Ejercico - <%= @practice.subject %></h2>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <% @questions.each_with_index do |question, i| %>
      <div class="row">
        <div class="small-12 columns">
          <strong>Pregunta <%= i+1 %>:</strong>
          <%= markdown question.question %>
        </div>
      </div>
      <div class="row">
        <div class="small-12 columns">
          <% question.correct_answer.each do |correct_answers| %>
            Respuesta correcta: <%= correct_answers.answer %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Regresar', admin_dashboard_path(anchor: 'ejercicios'), class: 'button tiny radius' %>
  </div>
</div>